import type {
  ArtifactPreviewResponse,
  BacktestLaunchOptionsView,
  BacktestReportView,
  BacktestsResponse,
  BenchmarkDetailView,
  BenchmarkListItemView,
  DatasetDeleteResponse,
  DatasetDependenciesResponse,
  DatasetRequestOptionsView,
  DatasetDetailView,
  DatasetListResponse,
  DatasetReadinessSummaryView,
  ExperimentsResponse,
  JobListResponse,
  JobStatusView,
  LaunchJobResponse,
  ModelComparisonView,
  OhlcvBarsResponse,
  RunDetailView,
  TrainingDatasetListResponse,
  TrainLaunchOptionsView,
  ModelTemplateListResponse,
  WorkbenchOverviewView,
} from "../shared/api/types";

export const experimentsFixture: ExperimentsResponse = {
  items: [
    {
      run_id: "smoke-train-run",
      model_name: "mean_baseline",
      dataset_id: "smoke_dataset",
      dataset_ids: ["smoke_dataset", "smoke_dataset_market_anchor"],
      datasets: [
        {
          dataset_id: "smoke_dataset",
          label: "Smoke Dataset",
          href: "/datasets/smoke_dataset",
          api_path: "/api/datasets/smoke_dataset",
          role: null,
          modality: "market",
        },
        {
          dataset_id: "smoke_dataset_market_anchor",
          label: "Smoke Market Anchor",
          href: "/datasets/smoke_dataset_market_anchor",
          api_path: "/api/datasets/smoke_dataset_market_anchor",
          role: null,
          modality: "market",
        },
      ],
      primary_dataset_id: "smoke_dataset",
      composition: null,
      family: "baseline",
      backend: "native",
      status: "success",
      created_at: "2026-04-07T10:41:36.862271+00:00",
      primary_metric_name: "mae",
      primary_metric_value: 0.0111,
      metrics: { mae: 0.0111 },
      backtest_count: 1,
      prediction_scopes: ["full"],
      tags: { dataset_id: "smoke_dataset" },
    },
    {
      run_id: "macro-signal-run",
      model_name: "macro_transformer",
      dataset_id: "macro_liquidity_snapshot",
      dataset_ids: ["macro_liquidity_snapshot"],
      datasets: [
        {
          dataset_id: "macro_liquidity_snapshot",
          label: "Macro Liquidity Snapshot",
          href: "/datasets/macro_liquidity_snapshot",
          api_path: "/api/datasets/macro_liquidity_snapshot",
          role: null,
          modality: "macro",
        },
      ],
      primary_dataset_id: "macro_liquidity_snapshot",
      composition: null,
      family: "transformer",
      backend: "torch",
      status: "success",
      created_at: "2026-04-07T11:41:36.862271+00:00",
      primary_metric_name: "mae",
      primary_metric_value: 0.0092,
      metrics: { mae: 0.0092 },
      backtest_count: 0,
      prediction_scopes: ["test"],
      tags: { dataset_id: "macro_liquidity_snapshot" },
    },
  ],
  total: 2,
  page: 1,
  per_page: 50,
  available_models: ["mean_baseline", "macro_transformer"],
  available_datasets: ["smoke_dataset", "macro_liquidity_snapshot"],
  available_statuses: ["success"],
};

export const benchmarkListFixture: BenchmarkListItemView[] = [
  {
    benchmark_name: "baseline_family_walk_forward",
    dataset_id: "baseline_real_benchmark_dataset",
    data_source: "binance_api",
    benchmark_type: "real_with_synthetic_reference",
    updated_at: "2026-04-07T10:41:36.862271+00:00",
    top_model_name: "elastic_net",
    top_model_score: 0.0034,
  },
];

export const jobsFixture: JobListResponse = {
  items: [
    {
      job_id: "job-dataset-1",
      job_type: "dataset_request",
      status: "success",
      created_at: "2026-04-08T08:00:00.000000+00:00",
      updated_at: "2026-04-08T08:04:00.000000+00:00",
      stages: [
        {
          name: "prepare",
          status: "success",
          summary: "Dataset prepared",
          started_at: "2026-04-08T08:00:00.000000+00:00",
          finished_at: "2026-04-08T08:04:00.000000+00:00",
        },
      ],
      result: {
        dataset_id: "smoke_dataset",
        run_ids: [],
        backtest_ids: [],
        benchmark_names: [],
        fit_result_uris: [],
        summary_artifacts: [],
        deeplinks: {
          run_detail: null,
          backtest_detail: null,
          review_detail: null,
          dataset_detail: "/datasets/smoke_dataset",
        },
      },
      error_message: null,
    },
    {
      job_id: "job-train-1",
      job_type: "train",
      status: "running",
      created_at: "2026-04-07T10:41:36.862271+00:00",
      updated_at: "2026-04-07T10:42:36.862271+00:00",
      stages: [
        {
          name: "prepare",
          status: "success",
          summary: "Dataset ready",
          started_at: "2026-04-07T10:41:36.862271+00:00",
          finished_at: "2026-04-07T10:42:00.862271+00:00",
        },
      ],
      result: {
        dataset_id: "smoke_dataset",
        run_ids: ["smoke-train-run"],
        backtest_ids: [],
        benchmark_names: [],
        fit_result_uris: [],
        summary_artifacts: [],
        deeplinks: {
          run_detail: "/runs/smoke-train-run",
          backtest_detail: null,
          review_detail: null,
        },
      },
      error_message: null,
    },
  ],
};

export const overviewFixture: WorkbenchOverviewView = {
  recent_runs: experimentsFixture.items,
  recent_backtests: [
    {
      backtest_id: "smoke-backtest",
      run_id: "smoke-train-run",
      model_name: "mean_baseline",
      status: "success",
      passed_consistency_checks: true,
      annual_return: 0.14,
      max_drawdown: -0.08,
      warning_count: 1,
      updated_at: "2026-04-07T10:45:00.000000+00:00",
    },
  ],
  recent_benchmarks: benchmarkListFixture,
  recent_jobs: [
    {
      job_id: "job-train-1",
      job_type: "train",
      status: "running",
      updated_at: "2026-04-07T10:42:36.862271+00:00",
      primary_stage: "prepare",
      deeplinks: { run_detail: "/runs/smoke-train-run" },
    },
  ],
  data_freshness: {
    dataset_id: "smoke_dataset",
    as_of_time: "2026-04-07T10:41:36.862271+00:00",
    freshness: "fresh",
    source: "tracking",
  },
  recommended_actions: [
    {
      key: "launch-train",
      title: "Launch Training",
      description: "Start training",
      target_path: "/runs",
    },
  ],
};

export const runDetailFixture: RunDetailView = {
  run_id: "smoke-train-run",
  model_name: "mean_baseline",
  dataset_id: "smoke_dataset",
  dataset_ids: ["smoke_dataset", "macro_liquidity_snapshot"],
  task_type: "regression",
  family: "baseline",
  backend: "native",
  status: "success",
  created_at: "2026-04-07T10:41:36.862271+00:00",
  metrics: { mae: 0.0111, rmse: 0.0222 },
  tracking_params: { dataset_id: "smoke_dataset" },
  manifest_metrics: { mae: 0.0111 },
  repro_context: { seed: 7 },
  dataset_summary: {
    dataset_type: "training_panel",
    data_domain: "market",
    data_domains: ["market"],
    entity_scope: "single_asset",
    entity_count: 1,
    feature_schema_hash: "feature-hash-v1",
    snapshot_version: "snapshot-v1",
    readiness_status: "ready",
    sample_count: 128,
    feature_count: 12,
    label_count: 128,
  },
  evaluation_summary: {
    task_type: "regression",
    selected_scope: "test",
    sample_count: 128,
    split_sample_counts: { train: 80, valid: 24, test: 24, full: 128 },
    regression_metrics: {
      mae: 0.0111,
      rmse: 0.0222,
      r2: 0.63,
      bias: -0.0012,
      sign_hit_rate: 0.67,
      valid_mae: 0.0134,
      sample_count: 24,
    },
    split_metrics: {
      train: { mae: 0.0091, rmse: 0.0181, r2: 0.71, sign_hit_rate: 0.7, sample_count: 80 },
      valid: { mae: 0.0134, rmse: 0.0251, r2: 0.58, sign_hit_rate: 0.62, sample_count: 24 },
      test: { mae: 0.0111, rmse: 0.0222, r2: 0.63, sign_hit_rate: 0.67, sample_count: 24 },
      full: { mae: 0.0108, rmse: 0.0217, r2: 0.65, sign_hit_rate: 0.68, sample_count: 128 },
    },
    coverage: {
      start_time: "2026-04-01T00:00:00Z",
      end_time: "2026-04-06T07:00:00Z",
      missing_samples: 0,
      available_scopes: ["train", "valid", "test", "full"],
    },
    feature_importance_summary: [
      { name: "price_momentum", value: 0.71 },
      { name: "volume_spike", value: 0.29 },
    ],
    series: {
      prediction_vs_target_timeseries: [
        { timestamp: "2026-04-05T00:00:00Z", prediction: 0.03, target: 0.025 },
        { timestamp: "2026-04-05T01:00:00Z", prediction: -0.012, target: -0.02 },
        { timestamp: "2026-04-05T02:00:00Z", prediction: 0.018, target: 0.01 },
      ],
      residual_timeseries: [
        { timestamp: "2026-04-05T00:00:00Z", residual: 0.005 },
        { timestamp: "2026-04-05T01:00:00Z", residual: 0.008 },
        { timestamp: "2026-04-05T02:00:00Z", residual: 0.008 },
      ],
      prediction_vs_target_scatter: [
        { prediction: 0.03, target: 0.025, timestamp: "2026-04-05T00:00:00Z" },
        { prediction: -0.012, target: -0.02, timestamp: "2026-04-05T01:00:00Z" },
        { prediction: 0.018, target: 0.01, timestamp: "2026-04-05T02:00:00Z" },
      ],
      residual_histogram: [
        { label: "-0.02 to -0.01", count: 1, center: -0.015 },
        { label: "0.00 to 0.01", count: 2, center: 0.005 },
      ],
    },
  },
  evaluation_artifacts: [
    {
      kind: "evaluation_summary",
      label: "evaluation summary",
      uri: "models/smoke-train-run/evaluation_summary.json",
      exists: true,
      previewable: true,
    },
  ],
  prediction_summary: {
    available_scopes: ["full", "test"],
    primary_scope: "test",
    sample_count: 152,
  },
  time_range: {
    start_time: "2026-04-01T00:00:00Z",
    end_time: "2026-04-06T07:00:00Z",
    selected_scope: "test",
  },
  feature_importance: { price_momentum: 0.71, volume_spike: 0.29 },
  predictions: [
    {
      scope: "full",
      sample_count: 128,
      uri: "predictions/smoke-train-run/full.json",
    },
    {
      scope: "test",
      sample_count: 24,
      uri: "predictions/smoke-train-run/test.json",
    },
  ],
  related_backtests: [
    {
      backtest_id: "smoke-backtest",
      model_name: "mean_baseline",
      run_id: "smoke-train-run",
      annual_return: 0.14,
      max_drawdown: -0.08,
      passed_consistency_checks: true,
    },
  ],
  artifacts: [
    {
      kind: "train_manifest",
      label: "train manifest",
      uri: "models/smoke-train-run/train_manifest.json",
      exists: true,
      previewable: true,
    },
    {
      kind: "evaluation_summary",
      label: "evaluation summary",
      uri: "models/smoke-train-run/evaluation_summary.json",
      exists: true,
      previewable: true,
    },
  ],
  notes: ["No review summary yet."],
  review_summary: {
    status: "unavailable",
    title: "Review not ready",
    summary: "N/A",
    suggested_actions: [],
  },
  warning_summary: { level: "none", count: 0, items: [] },
  glossary_hints: [{ key: "mae", term: "MAE", short: "mean absolute error" }],
};

export const artifactPreviewFixture: ArtifactPreviewResponse = {
  uri: "models/smoke-train-run/evaluation_summary.json",
  kind: "json",
  is_json: true,
  content: {
    task_type: "regression",
    selected_scope: "test",
    regression_metrics: {
      mae: 0.0111,
      rmse: 0.0222,
    },
  },
};

export const backtestsFixture: BacktestsResponse = {
  items: [
    {
      backtest_id: "smoke-backtest",
      run_id: "smoke-train-run",
      model_name: "mean_baseline",
      status: "success",
      passed_consistency_checks: true,
      annual_return: 0.14,
      max_drawdown: -0.08,
      warning_count: 1,
      updated_at: "2026-04-07T10:45:00.000000+00:00",
    },
  ],
  total: 1,
  page: 1,
  per_page: 50,
  available_statuses: ["success"],
};

export const backtestDetailFixture: BacktestReportView = {
  backtest_id: "smoke-backtest",
  model_name: "mean_baseline",
  run_id: "smoke-train-run",
  dataset_id: "smoke_dataset",
  dataset_ids: ["smoke_dataset", "macro_liquidity_snapshot"],
  template_id: "system::official_backtest_protocol_v1",
  official: true,
  protocol_version: "v1",
  protocol: {
    template: {
      template_id: "system::official_backtest_protocol_v1",
      name: "Official Backtest Protocol v1",
      description: "official protocol",
      source: "system",
      read_only: true,
      official: true,
      protocol_version: "v1",
      output_contract_version: "prediction_frame_v1",
      fixed_prediction_scope: "test",
      ranking_policy: "gate then compare",
      slice_policy: "same slice only",
      scenario_bundle: ["BASELINE", "COST_X2"],
      eligibility_rules: ["prediction frame required"],
      required_metadata: ["train_start_time", "train_end_time"],
      notes: ["official template cannot be deleted"],
    },
    gate_status: "warning",
    gate_results: [
      {
        key: "metadata_complete",
        label: "披露信息完整",
        passed: true,
        severity: "warning",
        detail: "训练窗口与训练元数据已披露。",
      },
      {
        key: "consistency_checks",
        label: "研究/仿真一致",
        passed: true,
        severity: "error",
        detail: "研究与仿真结果没有出现异常反转。",
      },
    ],
    rank_components: [
      {
        key: "annual_return",
        label: "Annual Return",
        value: 0.14,
        detail: "economic",
      },
      {
        key: "worst_scenario_return_delta",
        label: "Worst Scenario Delta",
        value: -0.05,
        detail: "robustness",
      },
    ],
    slice_id: "slice-1",
    slice_coverage: ["snapshot-v1", "1h", "return", "12", "test"],
    lookback_bucket: "90d-365d",
    actual_market_start_time: "2024-01-01T00:00:00Z",
    actual_market_end_time: "2026-04-11T02:00:00Z",
    actual_backtest_start_time: "2025-09-15T09:00:00Z",
    actual_backtest_end_time: "2026-04-11T02:00:00Z",
    actual_nlp_start_time: "2024-01-01T00:00:00Z",
    actual_nlp_end_time: "2026-04-11T01:35:00Z",
    official_benchmark_version: "official_reddit_pullpush_multimodal_v2_fusion:ad9386181319",
    official_window_days: 180,
    official_window_start_time: "2025-10-13T02:00:00Z",
    official_window_end_time: "2026-04-11T02:00:00Z",
    official_market_dataset_id: "baseline_real_benchmark_dataset",
    official_multimodal_dataset_id: "official_reddit_pullpush_multimodal_v2_fusion",
    nlp_gate_status: "passed",
    nlp_gate_reasons: [],
    metadata_summary: {
      train_start_time: "2025-01-01T00:00:00Z",
      train_end_time: "2025-12-31T00:00:00Z",
      lookback_window: "168",
      label_horizon: "12",
      modalities: "price, volume, macro",
      fusion_summary: "late fusion",
      random_seed: "7",
      tuning_trials: "24",
      external_pretraining: "yes",
      synthetic_data: "no",
    },
  },
  passed_consistency_checks: true,
  comparison_warnings: ["research and simulation have slight divergence on volatile period"],
  divergence_metrics: { annual_return_gap: 0.01 },
  scenario_metrics: { flash_crash: -0.12, liquidity_drain: -0.05 },
  research: {
    backtest_id: "smoke-backtest-research",
    engine_type: "research",
    report_summary: "research summary",
    metrics: {
      annual_return: 0.16,
      max_drawdown: -0.09,
      turnover_total: 1.2,
      implementation_shortfall: 0.01,
    },
    diagnostics: {},
    pnl_snapshot: { cumulative_return: 0.22 },
    positions: [],
    scenarios: [],
    warnings: [],
    artifacts: [],
  },
  simulation: {
    backtest_id: "smoke-backtest-simulation",
    engine_type: "simulation",
    report_summary: "simulation summary",
    metrics: {
      annual_return: 0.14,
      max_drawdown: -0.08,
      turnover_total: 1.1,
      implementation_shortfall: 0.02,
    },
    diagnostics: {},
    pnl_snapshot: { cumulative_return: 0.2 },
    positions: [
      { label: "2026-04-01", value: 0.4 },
      { label: "2026-04-02", value: 0.6 },
    ],
    scenarios: [],
    warnings: [],
    artifacts: [],
  },
  artifacts: [
    {
      kind: "report",
      label: "report",
      uri: "backtests/smoke-backtest/report.json",
      exists: true,
      previewable: true,
    },
  ],
  review_summary: {
    status: "unavailable",
    title: "Review not ready",
    summary: "N/A",
    suggested_actions: [],
  },
  warning_summary: { level: "medium", count: 1, items: ["research and simulation diverge"] },
  glossary_hints: [{ key: "max_drawdown", term: "Max Drawdown", short: "largest peak-to-trough decline" }],
};

export const benchmarkDetailFixture: BenchmarkDetailView = {
  benchmark_name: "baseline_family_walk_forward",
  dataset_id: "baseline_real_benchmark_dataset",
  data_source: "binance_api",
  benchmark_type: "real_with_synthetic_reference",
  updated_at: "2026-04-07T10:41:36.862271+00:00",
  window_count: 21,
  leaderboard: [
    {
      rank: 1,
      model_name: "elastic_net",
      family: "linear",
      advanced_kind: "baseline",
      backend: "native",
      window_count: 21,
      mean_valid_mae: 0.0031,
      mean_test_mae: 0.0034,
      artifact_uri: null,
    },
  ],
  results: [
    {
      rank: 1,
      model_name: "elastic_net",
      family: "linear",
      advanced_kind: "baseline",
      backend: "native",
      window_count: 21,
      mean_valid_mae: 0.0031,
      mean_test_mae: 0.0034,
      artifact_uri: null,
    },
  ],
  deep_backend_comparison: [],
  validation_summary: { top_model_consistent: true },
  artifacts: [
    {
      kind: "benchmark_json",
      label: "benchmark json",
      uri: "benchmarks/baseline_family_walk_forward.json",
      exists: true,
      previewable: true,
    },
  ],
  review_summary: {
    status: "unavailable",
    title: "Review not ready",
    summary: "N/A",
    suggested_actions: [],
  },
  warning_summary: { level: "none", count: 0, items: [] },
  glossary_hints: [{ key: "benchmark", term: "Benchmark", short: "model evaluation" }],
};

export const comparisonFixture: ModelComparisonView = {
  rows: [
    {
      row_id: "run:smoke-train-run",
      source_type: "run",
      label: "smoke-train-run",
      model_name: "mean_baseline",
      dataset_id: "smoke_dataset",
      backend: "native",
      status: "success",
      train_mae: 0.0111,
      mean_valid_mae: 0.0121,
      mean_test_mae: 0.0131,
      annual_return: 0.14,
      max_drawdown: -0.08,
      turnover_total: 1.1,
      implementation_shortfall: 0.02,
    },
    {
      row_id: "benchmark:baseline_family_walk_forward:elastic_net",
      source_type: "benchmark",
      label: "baseline_family_walk_forward / elastic_net",
      model_name: "elastic_net",
      dataset_id: "benchmark_dataset",
      backend: "native",
      status: "benchmark",
      train_mae: null,
      mean_valid_mae: 0.0104,
      mean_test_mae: 0.0119,
      annual_return: 0.18,
      max_drawdown: -0.06,
      turnover_total: 0.9,
      implementation_shortfall: 0.01,
    },
  ],
  metrics: [],
};

export const datasetsFixture: DatasetListResponse = {
  items: [
    {
      dataset_id: "smoke_dataset",
      display_name: "Smoke Dataset",
      subtitle: "最小可运行样本，用于训练链路和页面联调。",
      dataset_category: "演示训练面板",
      asset_id: "BTCUSDT",
      data_source: "binance",
      frequency: "1h",
      as_of_time: "2026-04-08T12:00:00Z",
      sample_count: 120,
      row_count: 120,
      feature_count: 6,
      label_count: 1,
      label_horizon: 12,
      split_strategy: "time",
      time_range_label: "2026-03-01 至 2026-04-08 · 1小时",
      source_vendor: "binance",
      exchange: "Binance",
      entity_scope: "single_asset",
      entity_count: 1,
      symbols_preview: ["BTCUSDT"],
      snapshot_version: "2026-04-08",
      quality_status: "healthy",
      readiness_status: "warning",
      build_status: "success",
      request_origin: "dataset_request",
      is_smoke: true,
      freshness: {
        as_of_time: "2026-04-08T12:00:00Z",
        data_start_time: "2026-03-01T00:00:00Z",
        data_end_time: "2026-04-08T12:00:00Z",
        lag_seconds: 30,
        status: "fresh",
        summary: "数据保持新鲜，适合联调和链路验证。",
      },
      temporal_safety_summary: "使用 as_of_time 切片，无前视泄漏。",
      links: [],
    },
    {
      dataset_id: "cross_asset_training_panel_v2",
      dataset_type: "training_panel",
      data_domain: "market",
      display_name: "Cross Asset Panel",
      subtitle: "多资产收益预测训练面板。",
      dataset_category: "多资产训练面板",
      asset_id: null,
      data_source: "binance",
      frequency: "4h",
      as_of_time: "2026-04-07T12:00:00Z",
      sample_count: 48200,
      row_count: 48200,
      feature_count: 64,
      label_count: 2,
      label_horizon: 6,
      split_strategy: "time_walk_forward",
      time_range_label: "2024-01-01 至 2026-04-07 · 4小时 · 多资产",
      source_vendor: "binance",
      exchange: "Binance",
      entity_scope: "multi_asset",
      entity_count: 8,
      symbols_preview: ["BTCUSDT", "ETHUSDT", "SOLUSDT"],
      snapshot_version: "2026-04-07",
      quality_status: "healthy",
      readiness_status: "ready",
      build_status: "success",
      request_origin: "catalog",
      is_smoke: false,
      freshness: {
        as_of_time: "2026-04-07T12:00:00Z",
        data_start_time: "2024-01-01T00:00:00Z",
        data_end_time: "2026-04-07T12:00:00Z",
        lag_seconds: 14400,
        status: "fresh",
        summary: "覆盖跨资产训练所需的统一面板，时间窗口较完整。",
      },
      temporal_safety_summary: "训练、验证、测试按时间滚动切分，具备基础时间安全约束。",
      links: [],
    },
    {
      dataset_id: "macro_liquidity_snapshot",
      display_name: "Macro Liquidity Snapshot",
      subtitle: "宏观流动性与风险偏好序列。",
      dataset_category: "宏观特征快照",
      asset_id: null,
      data_source: "fred",
      frequency: "1d",
      as_of_time: "2026-04-05T00:00:00Z",
      sample_count: 2360,
      row_count: 2360,
      feature_count: 12,
      label_count: 0,
      label_horizon: null,
      split_strategy: null,
      time_range_label: "2018-01-01 至 2026-04-05 · 日频",
      source_vendor: "fred",
      exchange: null,
      entity_scope: "macro_series",
      entity_count: 12,
      symbols_preview: [],
      snapshot_version: "2026-04-05",
      quality_status: "warning",
      readiness_status: "not_ready",
      build_status: "success",
      request_origin: "catalog",
      is_smoke: false,
      freshness: {
        as_of_time: "2026-04-05T00:00:00Z",
        data_start_time: "2018-01-01T00:00:00Z",
        data_end_time: "2026-04-05T00:00:00Z",
        lag_seconds: 86400,
        status: "stale",
        summary: "当前为日频更新，适合作为宏观背景变量，不适合近实时研究。",
      },
      temporal_safety_summary: "宏观序列按发布时间对齐，仍需关注修订值和 vintage 版本。",
      links: [],
    },
  ],
  total: 3,
  page: 1,
  per_page: 100,
};

export const datasetDetailFixture: DatasetDetailView = {
  dataset: datasetsFixture.items[0],
  display_name: "Smoke Dataset",
  subtitle: "最小可运行样本，用于训练链路和页面联调。",
  summary: "这是一份围绕 BTCUSDT 构建的 1 小时训练样本，适合用来验证训练、回测与前端页面的主链路。",
  intended_use: "适合做链路验收、页面联调和最小回归测试，不适合作为长期研究结论的数据基础。",
  risk_note: "样本窗口较短，只能说明链路是否正常，不能代表长期市场结构。",
  row_count: 120,
  feature_count: 6,
  label_count: 1,
  feature_columns_preview: [
    "lag_return_1",
    "volume_zscore",
    "sentiment_score_1h",
    "news_event_count_24h",
  ],
  label_columns: ["forward_return_1h"],
  feature_groups: [
    {
      key: "price_action",
      label: "价格行为特征",
      description: "帮助模型判断价格方向和收益变化。",
      count: 3,
      columns: ["lag_return_1", "momentum_3", "close_to_open"],
    },
    {
      key: "volume_liquidity",
      label: "成交与流动性特征",
      description: "帮助识别量能变化和流动性状态。",
      count: 2,
      columns: ["volume_zscore", "volume_ratio_3"],
    },
  ],
  quality_summary: {
    status: "healthy",
    summary: "数据质量整体稳定，可直接进入研究链路调试。",
    missing_ratio: 0,
    duplicate_ratio: 0,
    duplicate_rows: 0,
    checks: ["已基于 OHLCV 原始记录统计缺失与重复情况。"],
  },
  glossary_hints: [
    { key: "as_of_time", term: "as_of_time", short: "这份数据在什么可用时间点被冻结下来。" },
    { key: "feature_dimensions", term: "特征维度", short: "模型可用输入特征的数量和类别。" },
  ],
  label_spec: {
    target: "forward_return_1h",
    horizon: 12,
  },
  split_manifest: {
    train_rows: 80,
    valid_rows: 20,
    test_rows: 20,
    strategy: "time",
  },
  sample_policy: {
    frequency: "1h",
    asset_id: "BTCUSDT",
    min_history_bars: 48,
  },
  quality: {
    missing_ratio: 0,
    duplicate_ratio: 0,
    duplicate_rows: 0,
    status: "healthy",
    summary: "数据质量整体稳定，可直接进入研究链路调试。",
    checks: ["已基于 OHLCV 原始记录统计缺失与重复情况。"],
  },
  acquisition_profile: {
    request_name: "research-dataset-request",
    data_domain: "market",
    source_vendor: "Binance",
    exchange: "Binance",
    time_window: "2026-03-01 -> 2026-04-08",
    asset_mode: "single_asset",
    symbol_type: "spot",
    selection_mode: "manual_list",
    symbols: ["BTCUSDT"],
  },
  build_profile: {
    build_status: "success",
    snapshot_version: "2026-04-08",
    usable_sample_count: 120,
    dropped_rows: 0,
    entity_count: 1,
  },
  schema_profile: {
    feature_count: 6,
    label_count: 1,
    feature_schema_hash: "feature-hash-1",
    feature_dimension_consistent: true,
    missing_feature_policy: "fail",
  },
  readiness_profile: {
    readiness_status: "warning",
    readiness_reason: "Smoke dataset is valid for workflow verification but not for long-horizon research.",
  },
  training_profile: {
    sample_policy: "single_asset_strict",
    split_strategy: "time",
    entity_scope: "single_asset",
    label_horizon: 12,
    universe_summary: "BTCUSDT 单资产训练样本",
  },
  links: [
    {
      kind: "download",
      label: "获取该数据集",
      href: "/api/datasets/smoke_dataset/download",
      api_path: "/api/datasets/smoke_dataset/download",
    },
  ],
};

export const datasetRequestOptionsFixture: DatasetRequestOptionsView = {
  domains: [{ value: "market", label: "市场数据", recommended: true }],
  asset_modes: [
    { value: "single_asset", label: "单资产", recommended: true },
    { value: "multi_asset", label: "多资产" },
  ],
  symbol_types: [{ value: "spot", label: "现货", recommended: true }],
  selection_modes: [
    { value: "manual_list", label: "手动列表", recommended: true },
    { value: "top_n", label: "按数量选择" },
  ],
  source_vendors: [{ value: "binance", label: "Binance", recommended: true }],
  exchanges: [{ value: "Binance", label: "Binance", recommended: true }],
  frequencies: [
    { value: "1h", label: "1 小时", recommended: true },
    { value: "4h", label: "4 小时" },
  ],
  feature_sets: [{ value: "core_market_v1", label: "核心市场特征 v1", recommended: true }],
  label_horizons: [{ value: "12", label: "12 个 bar", recommended: true }],
  split_strategies: [{ value: "time_walk_forward", label: "时间滚动切分", recommended: true }],
  sample_policies: [{ value: "balanced", label: "平衡样本", recommended: true }],
  alignment_policies: [{ value: "entity_timestamp", label: "实体 + 时间戳对齐", recommended: true }],
  missing_feature_policies: [{ value: "fail", label: "关键特征缺失即失败", recommended: true }],
  constraints: {
    supports_market_only: true,
  },
};

export const datasetReadinessFixture: DatasetReadinessSummaryView = {
  dataset_id: "smoke_dataset",
  build_status: "success",
  readiness_status: "warning",
  blocking_issues: [],
  warnings: ["当前是 smoke 数据集，更适合联调与回归验证。"],
  raw_row_count: 120,
  usable_row_count: 120,
  dropped_row_count: 0,
  feature_count: 6,
  feature_schema_hash: "feature-hash-1",
  feature_dimension_consistent: true,
  entity_scope: "single_asset",
  entity_count: 1,
  alignment_status: "aligned",
  missing_feature_status: "pass",
  label_alignment_status: "pass",
  split_integrity_status: "pass",
  temporal_safety_status: "pass",
  freshness_status: "fresh",
  official_template_eligible: true,
  official_nlp_gate_status: "passed",
  official_nlp_gate_reasons: [],
  archival_nlp_source_only: true,
  nlp_requested_start_time: "2024-01-01T00:00:00Z",
  nlp_requested_end_time: "2026-04-11T02:00:00Z",
  nlp_actual_start_time: "2024-01-01T00:00:00Z",
  nlp_actual_end_time: "2026-04-11T01:35:00Z",
  market_window_start_time: "2024-01-01T00:00:00Z",
  market_window_end_time: "2026-04-11T02:00:00Z",
  official_backtest_start_time: "2025-09-15T09:00:00Z",
  official_backtest_end_time: "2026-04-11T02:00:00Z",
  nlp_coverage_ratio: 0.82,
  nlp_test_coverage_ratio: 0.91,
  nlp_max_consecutive_empty_bars: 12,
  nlp_duplicate_ratio: 0.01,
  nlp_entity_link_coverage_ratio: 0.98,
  recommended_next_actions: ["可以继续做训练前检查，但不建议把该数据集当成长期研究结论依据。"],
};

export const datasetNlpInspectionFixture = {
  dataset_id: "smoke_dataset",
  contains_nlp: true,
  coverage_summary:
    "NLP events are aligned by available_time and satisfy the official template quality gate.",
  requested_start_time: "2024-01-01T00:00:00Z",
  requested_end_time: "2026-04-11T02:00:00Z",
  actual_start_time: "2024-01-01T00:00:00Z",
  actual_end_time: "2026-04-11T01:35:00Z",
  source_vendors: ["news_archive", "reddit_archive", "gdelt"],
  keyword_summary: [
    { term: "ETF", count: 42, weight: 0.9 },
    { term: "halving", count: 31, weight: 0.7 },
  ],
  word_cloud_terms: [
    { term: "ETF", weight: 0.9 },
    { term: "halving", weight: 0.7 },
    { term: "liquidity", weight: 0.5 },
  ],
  source_breakdown: [
    { source: "news_archive", count: 120, share: 0.5 },
    { source: "reddit_archive", count: 84, share: 0.35 },
    { source: "gdelt", count: 36, share: 0.15 },
  ],
  event_timeline: [
    { label: "2026-04-09", event_count: 18, avg_sentiment: 0.12 },
    { label: "2026-04-10", event_count: 21, avg_sentiment: 0.08 },
    { label: "2026-04-11", event_count: 16, avg_sentiment: 0.11 },
  ],
  sentiment_distribution: [
    { label: "negative", value: 0.18 },
    { label: "neutral", value: 0.46 },
    { label: "positive", value: 0.36 },
  ],
  recent_event_previews: [
    {
      event_id: "news-1",
      title: "Bitcoin ETF inflow remains stable",
      snippet: "Archival news coverage shows ETF flow remained positive during the official test slice.",
      source: "news_archive",
      symbol: "BTCUSDT",
      event_time: "2026-04-11T01:00:00Z",
      available_time: "2026-04-11T01:15:00Z",
      sentiment_score: 0.21,
      url: "https://example.com/news-1",
    },
    {
      event_id: "reddit-1",
      title: "BTC discussion volume increased before CPI",
      snippet: "Historical Reddit export indicates rising discussion volume with neutral-to-positive tone.",
      source: "reddit_archive",
      symbol: "BTCUSDT",
      event_time: "2026-04-10T18:00:00Z",
      available_time: "2026-04-10T18:30:00Z",
      sentiment_score: 0.05,
      url: "https://example.com/reddit-1",
    },
  ],
  sample_feature_preview: {
    sentiment_score_1h: 0.18,
    news_event_count_24h: 14,
  },
  official_template_gate_status: "passed",
  official_template_gate_reasons: [],
  official_template_eligible: true,
  archival_source_only: true,
  coverage_ratio: 0.82,
  test_coverage_ratio: 0.91,
  max_consecutive_empty_bars: 12,
  duplicate_ratio: 0.01,
  entity_link_coverage_ratio: 0.98,
  market_window_start_time: "2024-01-01T00:00:00Z",
  market_window_end_time: "2026-04-11T02:00:00Z",
  official_backtest_start_time: "2025-09-15T09:00:00Z",
  official_backtest_end_time: "2026-04-11T02:00:00Z",
};

export const datasetDependenciesFixture: DatasetDependenciesResponse = {
  dataset_id: "smoke_dataset",
  items: [
    {
      dependency_kind: "data_asset",
      dependency_id: "market_ohlcv_btcusdt_1h",
      dependency_label: "BTCUSDT",
      target_dataset_id: null,
      direction: "depends_on",
      blocking: false,
      href: null,
      metadata: {},
    },
    {
      dependency_kind: "run",
      dependency_id: "smoke-train-run",
      dependency_label: "mean_baseline",
      target_dataset_id: "smoke_dataset",
      direction: "referenced_by",
      blocking: true,
      href: "/runs/smoke-train-run",
      metadata: {},
    },
  ],
  can_delete: false,
  delete_block_reasons: ["推荐数据集由系统维护，不能直接删除。"],
  protection_reason: "该数据集属于系统推荐集，前端不允许发起删除。",
  protection_kind: "recommended",
  blocking_items: [
    {
      dependency_kind: "run",
      dependency_id: "smoke-train-run",
      dependency_label: "mean_baseline",
      target_dataset_id: "smoke_dataset",
      direction: "referenced_by",
      blocking: true,
      href: "/runs/smoke-train-run",
      metadata: {},
    },
  ],
};

export const datasetDeleteFixture: DatasetDeleteResponse = {
  dataset_id: "smoke_dataset",
  status: "deleted",
  message: "Dataset was permanently deleted from the registry and local artifacts.",
  can_delete: true,
  blocking_items: [],
  deleted_files: ["artifacts/datasets/smoke_dataset_dataset_ref.json"],
};

export const trainingDatasetsFixture: TrainingDatasetListResponse = {
  items: [
    {
      dataset_id: "cross_asset_training_panel_v2",
      dataset_type: "training_panel",
      data_domain: "market",
      display_name: "跨资产收益训练面板 / Cross Asset Training Panel",
      snapshot_version: "2026-04-07",
      entity_scope: "multi_asset",
      universe_summary: {
        entity_scope: "multi_asset",
        entity_count: 8,
        symbols_preview: ["BTCUSDT", "ETHUSDT", "SOLUSDT"],
      },
      sample_count: 48200,
      feature_count: 64,
      label_count: 2,
      label_horizon: 6,
      split_strategy: "time_walk_forward",
      source_vendor: "binance",
      frequency: "4h",
      freshness_status: "fresh",
      quality_status: "healthy",
      readiness_status: "ready",
      readiness_reason: "后端确认特征、标签、切分和时间安全约束均满足训练最小条件。",
    },
    {
      dataset_id: "market_macro_onchain_fusion_v1",
      display_name: "多域融合训练面板 / Multi-domain Fusion Training Panel",
      dataset_type: "fusion_training_panel",
      data_domain: "market",
      snapshot_version: "2026-04-09",
      entity_scope: "multi_asset",
      universe_summary: {
        entity_scope: "multi_asset",
        entity_count: 8,
        symbols_preview: ["BTCUSDT", "ETHUSDT", "SOLUSDT"],
      },
      sample_count: 45120,
      feature_count: 81,
      label_count: 2,
      label_horizon: 6,
      split_strategy: "time_walk_forward",
      source_vendor: "binance+fred+defillama",
      frequency: "4h",
      freshness_status: "fresh",
      quality_status: "healthy",
      readiness_status: "ready",
      readiness_reason: "市场、宏观与链上特征已按 available_time 安全对齐，可直接进入融合训练。",
    },
    {
      dataset_id: "smoke_dataset",
      dataset_type: "training_panel",
      data_domain: "market",
      display_name: "链路联调训练样本 / Smoke Training Sample",
      snapshot_version: "2026-04-08",
      entity_scope: "single_asset",
      universe_summary: {
        entity_scope: "single_asset",
        entity_count: 1,
        symbols_preview: ["BTCUSDT"],
      },
      sample_count: 120,
      feature_count: 6,
      label_count: 1,
      label_horizon: 12,
      split_strategy: "time",
      source_vendor: "binance",
      frequency: "1h",
      freshness_status: "fresh",
      quality_status: "healthy",
      readiness_status: "warning",
      readiness_reason: "适合联调与链路验证，不适合长期研究。",
    },
    {
      dataset_id: "macro_liquidity_snapshot",
      dataset_type: "feature_snapshot",
      data_domain: "macro",
      display_name: "宏观流动性快照 / Macro Liquidity Snapshot",
      snapshot_version: "2026-04-05",
      entity_scope: "macro_series",
      universe_summary: {
        entity_scope: "macro_series",
        entity_count: 12,
        symbols_preview: ["DXY", "VIX", "CPI"],
      },
      sample_count: 2360,
      feature_count: 12,
      label_count: 0,
      label_horizon: null,
      split_strategy: null,
      source_vendor: "fred",
      frequency: "1d",
      freshness_status: "stale",
      quality_status: "warning",
      readiness_status: "not_ready",
      readiness_reason: "缺少标签列，当前只适合作为背景因子浏览。",
    },
  ],
  total: 4,
};

export const datasetOhlcvFixture: OhlcvBarsResponse = {
  dataset_id: "smoke_dataset",
  asset_id: "BTCUSDT",
  symbol: "BTCUSDT",
  frequency: "1h",
  total: 2,
  page: 1,
  per_page: 300,
  start_time: null,
  end_time: null,
  items: [
    {
      event_time: "2026-04-08T11:00:00Z",
      available_time: "2026-04-08T11:01:00Z",
      symbol: "BTCUSDT",
      venue: "binance",
      open: 100,
      high: 101,
      low: 99,
      close: 100.5,
      volume: 1500,
    },
    {
      event_time: "2026-04-08T12:00:00Z",
      available_time: "2026-04-08T12:01:00Z",
      symbol: "BTCUSDT",
      venue: "binance",
      open: 100.5,
      high: 102,
      low: 100,
      close: 101.8,
      volume: 1700,
    },
  ],
};

export const trainOptionsFixture: TrainLaunchOptionsView = {
  dataset_presets: [{ value: "smoke", label: "smoke", description: null, recommended: true }],
  model_options: [{ value: "elastic_net", label: "Elastic Net", description: null, recommended: true }],
  template_options: [
    {
      value: "registry::elastic_net",
      label: "Elastic Net default",
      description: "Template sourced from model registry.",
      recommended: true,
    },
  ],
  trainer_presets: [{ value: "fast", label: "fast", description: null, recommended: true }],
  default_seed: 7,
  constraints: {},
};

export const modelTemplatesFixture: ModelTemplateListResponse = {
  items: [
    {
      template_id: "registry::elastic_net",
      name: "Elastic Net default",
      model_name: "elastic_net",
      description: "Template sourced from model registry.",
      source: "registry",
      hyperparams: { alpha: 0.001, l1_ratio: 0.5 },
      trainer_preset: "fast",
      dataset_preset: "smoke",
      read_only: true,
      model_registered: true,
      deleted_at: null,
      created_at: "2026-04-08T12:00:00Z",
      updated_at: "2026-04-08T12:00:00Z",
    },
    {
      template_id: "custom-template-1",
      name: "Custom Elastic Net",
      model_name: "elastic_net",
      description: "Custom template for training launches.",
      source: "custom",
      hyperparams: { alpha: 0.01, l1_ratio: 0.3 },
      trainer_preset: "fast",
      dataset_preset: "real_benchmark",
      read_only: false,
      model_registered: true,
      deleted_at: null,
      created_at: "2026-04-08T12:05:00Z",
      updated_at: "2026-04-08T12:05:00Z",
    },
  ],
  total: 2,
  model_options_source: "registry",
};

export const backtestOptionsFixture: BacktestLaunchOptionsView = {
  default_mode: "official",
  official_template_id: "system::official_backtest_protocol_v1",
  template_options: [
    {
      template_id: "system::official_backtest_protocol_v1",
      name: "Official Backtest Protocol v1",
      description: "official protocol",
      source: "system",
      read_only: true,
      official: true,
      protocol_version: "v1",
      output_contract_version: "prediction_frame_v1",
      fixed_prediction_scope: "test",
      ranking_policy: null,
      slice_policy: null,
      scenario_bundle: ["BASELINE"],
      eligibility_rules: [],
      required_metadata: [],
      notes: [],
    },
  ],
  dataset_presets: [{ value: "smoke", label: "smoke", description: null, recommended: true }],
  prediction_scopes: [{ value: "full", label: "full", description: null, recommended: true }],
  strategy_presets: [{ value: "sign", label: "sign", description: null, recommended: true }],
  portfolio_presets: [
    { value: "research_default", label: "research_default", description: null, recommended: true },
  ],
  cost_presets: [{ value: "standard", label: "standard", description: null, recommended: true }],
  default_benchmark_symbol: "BTCUSDT",
  constraints: {},
};

export const launchJobFixture: LaunchJobResponse = {
  job_id: "job-new-1",
  status: "queued",
  job_api_path: "/api/jobs/job-new-1",
  tracking_token: "job-new-1",
  submitted_at: "2026-04-08T12:00:00Z",
};

export const jobStatusFixture: JobStatusView = {
  job_id: "job-new-1",
  job_type: "train",
  status: "success",
  created_at: "2026-04-08T12:00:00Z",
  updated_at: "2026-04-08T12:01:00Z",
  stages: [
    {
      name: "train",
      status: "success",
      summary: "done",
      started_at: "2026-04-08T12:00:00Z",
      finished_at: "2026-04-08T12:01:00Z",
    },
  ],
  result: {
    dataset_id: "smoke_dataset",
    run_ids: ["smoke-train-run"],
    backtest_ids: [],
    benchmark_names: [],
    fit_result_uris: [],
    summary_artifacts: [],
    deeplinks: {
      run_detail: "/runs/smoke-train-run",
      backtest_detail: null,
      review_detail: null,
    },
    result_links: [],
    summary: null,
    pipeline_summary: null,
  },
  error_message: null,
};
